### ISSUE TITLE
BOT_TOKEN和GROUP_id是怎么获取的呢

### ISSUE THREAD

**Issue by GarraWong** [jw-star/pornbot91_py#1]
获取了appid和hash了

**Comment by jw-star** [comment]
> 获取了appid和hash了

bot_token是机器人的token(https://t.me/botfather 找他要)，

GROUP_id是群组id，定时任务会发到这个群，转发你的频道或者群组消息给@get_id_bot，会发你群组id

**Comment by GarraWong** [comment]
感谢回复，bot已经找botfaher获取到了。

**Comment by GarraWong** [comment]
还有个问题请教一下，机器人不需要做任何编码吗。
在获取机器人的过程中，我看教程有教机器人做复读机，你发送消息，他会回复相同详细的JS代码。在这个python项目里，这个机器人申请了以后，不需要做任何编码吗

**Comment by jw-star** [comment]
不需要

> 还有个问题请教一下，机器人不需要做任何编码吗。 在获取机器人的过程中，我看教程有教机器人做复读机，你发送消息，他会回复相同详细的JS代码。在这个python项目里，这个机器人申请了以后，不需要做任何编码吗
