### ISSUE TITLE
发送链接以后未打印正在下载中

### ISSUE THREAD

**Issue by GarraWong** [jw-star/pornbot91_py#2]
日志：

消息已被删除或不存在，无法转发

[0310/021553.599493:ERROR:stack_trace_posix.cc(659)] Failed to parse the contents of /proc/self/maps

[0310/021553.787202:ERROR:stack_trace_posix.cc(659)] Failed to parse the contents of /proc/self/maps

[0310/021553.812884:FATAL:zygote_main_linux.cc(163)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 

#0 0x0040046508ec base::debug::StackTrace::StackTrace()

#1 0x0040045cc200 logging::LogMessage::~LogMessage()

#2 0x004005ac0e8a service_manager::ZygoteMain()

#3 0x004004292512 content::RunZygote()

#4 0x0040042938cd content::ContentMainRunnerImpl::Run()

#5 0x0040042c6fbb service_manager::Main()

#6 0x004004291d91 content::ContentMain()

#7 0x00400879997d headless::(anonymous namespace)::RunContentMain()

#8 0x00400879982e headless::RunChildProcessIfNeeded()

#9 0x0040042c3245 headless::HeadlessShellMain()

#10 0x0040026891ac ChromeMain

#11 0x00400ca4709b __libc_start_main

#12 0x00400268902a _start

Received signal 6

#0 0x0040046508ec base::debug::StackTrace::StackTrace()

#1 0x004004650451 base::debug::(anonymous namespace)::StackDumpSignalHandler()

#2 0x00400a758730 <unknown>

#3 0x00400ca5a7bb gsignal

#4 0x00400ca45535 abort

#5 0x00400464f275 base::debug::BreakDebugger()

#6 0x0040045cc669 logging::LogMessage::~LogMessage()

#7 0x004005ac0e8a service_manager::ZygoteMain()

#8 0x004004292512 content::RunZygote()

#9 0x0040042938cd content::ContentMainRunnerImpl::Run()

#10 0x0040042c6fbb service_manager::Main()

#11 0x004004291d91 content::ContentMain()

#12 0x00400879997d headless::(anonymous namespace)::RunContentMain()

#13 0x00400879982e headless::RunChildProcessIfNeeded()

#14 0x0040042c3245 headless::HeadlessShellMain()

#15 0x0040026891ac ChromeMain

#16 0x00400ca4709b __libc_start_main

#17 0x00400268902a _start

  r8: 0000000000000000  r9: 000000400a707da0 r10: 0000000000000008 r11: 000000400cbad4a0

 r12: 000000400a708640 r13: 000000000000006f r14: 000000400a708648 r15: 000000400a708650

  di: 0000000000000002  si: 000000400a707da0  bp: 000000400a707ff0  bx: 0000000000000006

  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000027  sp: 000000400a707da0

  ip: 000000400ca5a7bb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000

 trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000

[end of stack trace]

Calling _exit(1). Core file will not be generated.

[0310/021554.303398:ERROR:file_path_watcher_linux.cc(276)] inotify_init() failed: Function not implemented (38)

[0310/021554.491475:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:58473/devtools/browser/aa9c620c-0962-4419-8930-22fa8d8378d0

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

qemu: unknown option 'type=gpu-process'

**Comment by jw-star** [comment]
在哪个环境下运行的，如果是docker，不会出现该问题一般  ， 可能和这里有关，                    '-–disable-gpu',

**Comment by jw-star** [comment]
这是我运行docker的环境： Ubuntu 18.04

**Comment by GarraWong** [comment]
> 在哪个环境下运行的，如果是docker，不会出现该问题一般 ， 可能和这里有关， '-–disable-gpu',
操作系统 MacOS 12 Monterey
python 3.9
Docker Desktop for Mac 官网最新版本
修改了docker-compose.yml 里redis和telegram相关的配置。
在项目根目录执行 docker compose up
向机器人发送/start 后，再发送浏览器地址栏的地址后，docker destop  dashboard看到的日志就是上面的了

**Comment by GarraWong** [comment]
> 这是我运行docker的环境： Ubuntu 18.04

补充一点 2020款 Apple silicon arm芯片

**Comment by jw-star** [comment]
> > 这是我运行docker的环境： Ubuntu 18.04
> 
> 补充一点 2020款 Apple silicon arm芯片

请手动编译该项目，我编译好的只适合amd64

**Comment by jw-star** [comment]
如果本地使用 可以只运行redis，然后本地启动python项目   或者买一台vultr的vps做测试可以
