### ISSUE TITLE
Mac本地构建过后仍然不行

### ISSUE THREAD

**Issue by GarraWong** [jw-star/pornbot91_py#3]
使用Mac在本地构建镜像后，推送到我的个人仓库中，再修改了本项目提供的docker-compose.yml部署

在构建的时候报过错，我在宿主机定义了sources.list改为了清华的源

> ```txt
> #默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
> deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free
> #deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free
> deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free
> #deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free
> 
> deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free
> #deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free
> 
> deb https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free
> #deb-src https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free
> 
> 本项目dockerfile里提供的python镜像，我在hub里追溯到最原始基础镜像使用的是debian，源应该是没问题的
> ```
> 

新问题为：

> [INFO] Beginning extraction
> 
> [INFO] Chromium extracted to: /root/.local/share/pyppeteer/local-chromium/588429
> 
> qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
> 
> qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
> 
> qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
> 
> qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
> 
> Unhandled exception on echo_all
> 
> Traceback (most recent call last):
> 
>   File "/app/pyp/page91.py", line 17, in getVideoInfo91
> 
>     browser, page = await ini_browser()
> 
>   File "/app/pyp/page91.py", line 55, in ini_browser
> 
>     browser = await launch(headless=True, dumpio=True, devtools=False,
> 
>   File "/root/.local/lib/python3.10/site-packages/pyppeteer/launcher.py", line 307, in launch
> 
>     return await Launcher(options, **kwargs).launch()
> 
>   File "/root/.local/lib/python3.10/site-packages/pyppeteer/launcher.py", line 168, in launch
> 
>     self.browserWSEndpoint = get_ws_endpoint(self.url)
> 
>   File "/root/.local/lib/python3.10/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
> 
>     raise BrowserError('Browser closed unexpectedly:\n')
> 
> pyppeteer.errors.BrowserError: Browser closed unexpectedly:
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> 
>   File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 51, in __call__
> 
>     result = await fn(*args, **kwargs)
> 
>   File "/app/pyp/page91.py", line 40, in getVideoInfo91
> 
>     await page.close()
> 
> UnboundLocalError: local variable 'page' referenced before assignment
> 
> 
> The above exception was the direct cause of the following exception:
> 
> 
> Traceback (most recent call last):
> 
>   File "/root/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
> 
>     await callback(event)
> 
>   File "/app/pornbot.py", line 73, in echo_all
> 
>     videoinfo = await page91.getVideoInfo91(viewkey_url)
> 
>   File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 86, in async_wrapped
> 
>     return await fn(*args, **kwargs)
> 
>   File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 48, in __call__
> 
>     do = self.iter(retry_state=retry_state)
> 
>   File "/root/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 361, in iter
> 
>     raise retry_exc from fut.exception()
> 
> tenacity.RetryError: RetryError[<Future at 0xffffb639b8b0 state=finished raised UnboundLocalError>]
> 
> Run time of job "page91DownIndex (trigger: cron[hour='6', minute='50'], next run at: 2022-03-12 06:50:00 CST)" was missed by 7:38:37.828558
> 
> Traceback (most recent call last):
> 
>   File "/app/pornbot.py", line 154, in <module>
> 
>     bot.run_until_disconnected()
> 
>   File "/root/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 84, in run_until_disconnected
> 
>     return self.loop.run_until_complete(self._run_until_disconnected())
> 
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
> 
>     self.run_forever()
> 
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
> 
>     self._run_once()
> 
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1845, in _run_once
> 
>     event_list = self._selector.select(timeout)
> 
>   File "/usr/local/lib/python3.10/selectors.py", line 469, in select
> 
>     fd_event_list = self._selector.poll(timeout, max_ev)
> 
>   File "/root/.local/lib/python3.10/site-packages/pyppeteer/launcher.py", line 153, in _close_process
> 
>     self._loop.run_until_complete(self.killChrome())
> 
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 617, in run_until_complete
> 
>     self._check_running()
> 
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 577, in _check_running
> 
>     raise RuntimeError('This event loop is already running')
> 
> RuntimeError: This event loop is already running

在里面有三点我自己尝试了一下解决，但是没有找到解决办法。
一个是

> `/lib64/ld-linux-x86-64.so.2`的缺失，搜索了一圈网上，都是说的是被误删之后只能执行cd，ls命令之类的

第二是 

> `pyppeteer.errors.BrowserError: Browser closed unexpectedly`，针对这个问题，我搜索了，在如下网址：
> [https://stackoverflow.com/questions/57217924/pyppeteer-errors-browsererror-browser-closed-unexpectedly](https://stackoverflow.com/questions/57217924/pyppeteer-errors-browsererror-browser-closed-unexpectedly)
> 
> [https://github.com/puppeteer/puppeteer/issues/2462](https://stackoverflow.com/questions/57217924/pyppeteer-errors-browsererror-browser-closed-unexpectedly)
> 
> [https://github.com/miyakogi/pyppeteer/issues/82](https://stackoverflow.com/questions/57217924/pyppeteer-errors-browsererror-browser-closed-unexpectedly)
> 
> 里面提到的所有的解决办法几乎都为apt-get依赖的问题
> 
> > `udo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`
> 
> 我手动对比了网站提供的依赖与本项目的dockerfile，网站提供的依赖，只有wget是项目中的不存在的。

第三个问题是`UnboundLocalError: local variable 'page' referenced before assignment` 这个问题我搜了一下感觉是初学者才会犯的那种的问题，所以排除

还尝试过的解决办法有：

> 修改lanuch方法里的启动参数 注释掉`-–disable-gpu`

我还有另一个想法就是

> `TelegramClient(...)`加上代理会不会有效果。我用的是ClashX，它的yaml文件有ip和端口。

今晚另有一个发现：

> 在https://doesitarm.com/ 搜索python 看到提供的最大版本号为python3.9，而dockerfile里基础镜像是3.10，不知道会不会有问题，因为我这网不太好，构建本地镜像太慢，就还没试。

大哥有空看一下，如果有思路可以给我沟通一下。
都整到这里了，已经不是看不成h片的问题了，刚还在京东上购买了几本python的书

**Comment by jw-star** [comment]
好的，你在telegram联系我 @bzhzq，可以交流下python,我也是兴趣 @GarraWong
